# pyproject.toml

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "tests"
addopts = "--cov=src --cov-report=html:tests/htmlcov"

[tool.pylint.'MASTER']
init-hook = 'import sys; sys.path.append("src")'
